"""Drop field_value from index due to B-Tree size limits

Revision ID: 6f82afa69dc9
Revises: 002_drop_tsvector
Create Date: 2026-08-11 10:29:33.083129
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f82afa69dc9'
down_revision: Union[str, None] = '002_drop_tsvector'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_extracted_fields_field_name_value'), table_name='extracted_fields')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_extracted_fields_field_name_value'), 'extracted_fields', ['field_name', 'field_value'], unique=False)
    # ### end Alembic commands ###
